//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppDbFirstApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string accountId { get; set; }
        public string bankId { get; set; }
        public string accountNumber { get; set; }
        public int accountType { get; set; }
        public decimal balance { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int status { get; set; }
        public string customerId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
