//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppDbFirstApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.Accounts = new HashSet<Account>();
            this.Currencies = new HashSet<Currency>();
            this.Employees = new HashSet<Employee>();
            this.Transactions = new HashSet<Transaction>();
            this.Transactions1 = new HashSet<Transaction>();
        }
    
        public string bankId { get; set; }
        public string bankname { get; set; }
        public string branch { get; set; }
        public string ifsc { get; set; }
        public decimal selfRTGS { get; set; }
        public decimal selfIMPS { get; set; }
        public decimal otherRTGS { get; set; }
        public decimal otherIMPS { get; set; }
        public decimal balance { get; set; }
        public string defaultCurrencyName { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Currency> Currencies { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Transaction> Transactions1 { get; set; }
    }
}
